name: End-to-End Tests

on: [push]

jobs:
  e2e:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Cypress Run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          wait-on: "http://localhost:3000"

          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
