name: Tests

on: [push, pull_request]

jobs:
  e2e-and-unit:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Create app directory from template
        run: npx create-react-app test-app --use-npm --template file:../cra-template-crows

      - name: Run our Cypress E2E tests
        uses: cypress-io/github-action@v1
        with:
          # Passing environment variables here will pass them as Cypress Environment Variables (https://docs.cypress.io/guides/guides/environment-variables.html), and will not be accessible to the start script
          # env: DATABASE_URL=${{ secrets.DATABASE_URL }}

          working-directory: ./test-app
          start: npm start
          wait-on: "http://localhost:3000"

          record: false
        env:
          # These environment variables will be picked up by the start script
          REACT_APP_FIREBASE_DATABASE_URL: ${{ secrets.REACT_APP_FIREBASE_DATABASE_URL }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}

      - name: Run unit tests with coverage
        run: npm run unit-test
        env:
          CI: true
        working-directory: ./test-app

      - name: Merge our test reports
        run: npx merge-cypress-jest-coverage
        working-directory: ./test-app

      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: test-app/
